connector.name=iceberg
iceberg.catalog.type=rest
# The URI of the Polaris REST server
iceberg.rest-catalog.uri=http://localhost:8181/api/catalog
# The name of the catalog you will create in Polaris
iceberg.rest-catalog.warehouse=warehouse

# S3 / MinIO Connection
fs.native-s3.enabled=true

s3.max-connections=50
s3.region=us-east-1
s3.endpoint=http://localhost:9000
s3.path-style-access=true
s3.aws-access-key=admin
s3.aws-secret-key=password

# Security (Polaris requires OAuth2)
iceberg.rest-catalog.security=OAUTH2
iceberg.rest-catalog.oauth2.credential=root:secret
iceberg.rest-catalog.oauth2.scope=PRINCIPAL_ROLE:ALL
iceberg.register-table-procedure.enabled=true